### ISSUE TITLE
Missing icon/image

### ISSUE THREAD

**Issue by Pulpyyyy** [Matthyeux/train-traveler#8]
With version 0.1.0 alpha 1
![image](https://github.com/Matthyeux/train-traveler/assets/32004297/263f55d6-6c31-4e10-98b0-666e4f5b7c44)
Regards

**Comment by Matthyeux** [comment]
Thank you for the report !

It is fixed in version `0.1.0-alpha.2`.

It was a wrong name format for the component's directory. Unfortunately, you need to delete the integration from the UI and download it again to make it works.

Sorry for the inconvenience
